module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: [''🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚','💬','🔍','🥺','⚡','❤️','😉','🤔','🙃','📩','🌐','🔸','👑','🇵🇰'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EjDAkoGV1LQ6ybXd8ABzQZ',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/4xjhiz.jpeg',
    NEWSLETTER_JID: '120363402507750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'TF MD BOT',
    OWNER_NAME: 'Tahir Iqbal',
    OWNER_NUMBER: '923404923915',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> HACKER TF',
    CHANNEL_LINK: 'https://chat.whatsapp.com/EjDAkoGV1LQ6ybXd8ABzQZ',
};
